### ISSUE TITLE
Add -e <endpoint> to example?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-indexer#5]
Can't do it my self, since I don't understand it fully.

`-e, --endpoint <endpoint> `
to this one
`$ norch-indexer -d testdata/ -f places,topics,organisations`

**Comment by eklem** [comment]
Or just explain, and I'll update doc.

**Comment by eklem** [comment]
Added endpoint to example
https://github.com/fergiemcdowall/norch-indexer/blob/master/README.md

**Comment by fergiemcdowall** [comment]
Great! :+1:
