### ISSUE TITLE
Creating duplicates or wrong "total docs"?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-indexer#7]
Currently I'm re-indexing "everything" in my solution. Every document has an ID before they're sent of to the indexer, so the old, indexed documents should be overwritten/edited, instead of being created as duplicates of old ones.

It may seem like there are no duplicates when looking at search results, but the "total docs"-number is increasing for each time I run the indexing-process.

Search result _before_ indexing another round `1044 totalDocs`:
![skjermbilde 2015-03-08 kl 16 20 43](https://cloud.githubusercontent.com/assets/236656/6546334/6560e98a-c5b0-11e4-819c-5961bc0f357a.png)

Search result _after_ indexing another round ´1115 totalDocs´:
![skjermbilde 2015-03-08 kl 16 23 20](https://cloud.githubusercontent.com/assets/236656/6546350/cb54d350-c5b0-11e4-89bc-d39f4241d137.png)

I've checked, and the same amount of docs are sent to the ´norch-indexer´ (86 docs) and they have the same ID. So, not every document re-indexed is duplicated.

The index also increases in size:

```
pi@fatboy ~ $ cd si/
pi@fatboy ~/si $ du -h
5.4M    .
pi@fatboy ~/si $ cd ..
pi@fatboy ~ $ node lifeindex/li-twitter-tweets.js
pi@fatboy ~ $ cd si/
pi@fatboy ~/si $ du -h
5.5M    .
pi@fatboy ~/si $
```

**Comment by eklem** [comment]
And this is how I fire up the indexer:

```
  //Index file with exec
  var exec = require('child_process').exec;
  exec('node /home/pi/node_modules/.bin/norch-indexer -d /home/pi/lifeindex/li-twitter-tweets/ -f type,user,tags','utf8', function (error, stdout, stderr) {
    // output is in stdout
    //console.log(stdout)
    //console.log(error)
    //console.log(stderr)
  });
```

**Comment by fergiemcdowall** [comment]
Hmmm.

Since you are using `exec()`, I wonder if the quickest route is to start using `curl` commands instead?

**Comment by eklem** [comment]
Ahh, thanks! Didn't think of that. Only thought of using curl from inside script and that seemed a bit too complex for me. I'll try that.

**Comment by eklem** [comment]
I'll test that and see if that works better!

**Comment by eklem** [comment]
As we discussed offline. The absolute best alternative for my use case is to use the `search-index` API:
https://github.com/fergiemcdowall/search-index#user-content-siadd

**Comment by eklem** [comment]
I can test this manually from command-line, indexing the same JSON-file over again a couple of times. If it creates duplicates, we can keep this issue open?

**Comment by eklem** [comment]
Managed to reproduce part of this on [search-index](https://github.com/fergiemcdowall/search-index/issues/80), but not sure if the index increases or not. It varies a little up and down, but I have to stop and start `norch` and starting it does something to the size of the index, so only the document count that increases steady in the new issue. Anyway, this is most probably not a `norch-indexer` issue.
